name: PR Validation

on:
  pull_request:
    branches: [main]

jobs:
  build-and-test:
    name: Build & Test
    uses: ./.github/workflows/build-and-test.yml
    with:
      commit-hash: ${{ github.sha }}
